"""Catálogo base de contactos nacionales de emergencia en Colombia."""

EMERGENCY_CONTACTS: list[dict[str, object]] = [
    {
        "code": "national_emergency",
        "name": "Línea única de emergencias",
        "description": (
            "Canal central que coordina policía, bomberos, ambulancias y gestión de emergencias."
        ),
        "phone_number": "123",
        "category": "security",
        "is_primary": True,
        "is_national": True,
    },
    {
        "code": "police",
        "name": "Policía Nacional",
        "description": "Atención de delitos, violencia y orden público.",
        "phone_number": "112",
        "category": "security",
        "is_primary": True,
        "is_national": True,
    },
    {
        "code": "firefighters",
        "name": "Bomberos",
        "description": "Incendios, rescates y emergencias con materiales peligrosos.",
        "phone_number": "119",
        "category": "disaster",
        "is_primary": True,
        "is_national": True,
    },
    {
        "code": "ambulance",
        "name": "Ambulancias",
        "description": "Atención médica urgente y traslado de pacientes.",
        "phone_number": "125",
        "category": "health",
        "is_primary": True,
        "is_national": True,
    },
    {
        "code": "civil_defense",
        "name": "Defensa Civil",
        "description": "Apoyo en desastres naturales y rescates.",
        "phone_number": "132",
        "category": "disaster",
        "is_primary": False,
        "is_national": True,
    },
    {
        "code": "red_cross",
        "name": "Cruz Roja",
        "description": "Primeros auxilios y apoyo humanitario.",
        "phone_number": "144",
        "category": "health",
        "is_primary": False,
        "is_national": True,
    },
    {
        "code": "women_support",
        "name": "Línea violencia contra la mujer",
        "description": "Orientación y atención a víctimas de violencia.",
        "phone_number": "155",
        "category": "social",
        "is_primary": False,
        "is_national": True,
    },
    {
        "code": "children_protection",
        "name": "ICBF",
        "description": "Protección de niños, niñas y adolescentes.",
        "phone_number": "141",
        "category": "social",
        "is_primary": False,
        "is_national": True,
    },
    {
        "code": "anti_extortion",
        "name": "GAULA",
        "description": "Denuncias por extorsión y secuestro.",
        "phone_number": "165",
        "category": "security",
        "is_primary": False,
        "is_national": True,
    },
]
