class Collections:
    USERS = "users"
    EXPERIENCES = "experiences"
    SCHEDULES = "schedules"
    RESERVATIONS = "reservations"
    PARTICIPANTS = "participants"
    PAYMENT_PROOFS = "payment_proofs"
    EQUINES = "equines"
    SADDLES = "saddles"
    ASSIGNMENTS = "assignments"
    SERVICE_LOGS = "service_logs"
    PROVIDERS = "providers"
    POLICIES = "policies"
    SUPPLIES = "supplies"
    APP_CONFIG = "app_config"
