class ErrorCode:
    VALIDATION_ERROR = "common.validation_error"
    RESOURCE_NOT_FOUND = "common.resource_not_found"
    METHOD_NOT_ALLOWED = "common.method_not_allowed"
    CONFLICT = "common.conflict"
    INTERNAL_ERROR = "common.internal_error"

    AUTH_INVALID_CREDENTIALS = "auth.invalid_credentials"
    AUTH_INACTIVE_USER = "auth.inactive_user"
    AUTH_INVALID_TOKEN = "auth.invalid_token"
    AUTH_EXPIRED_TOKEN = "auth.expired_token"
    AUTH_FORBIDDEN = "auth.forbidden"
    AUTH_PASSWORD_MISMATCH = "auth.password_mismatch"
    AUTH_UNAUTHORIZED = "auth.unauthorized"

    USER_EMAIL_ALREADY_EXISTS = "user.email_already_exists"
    USER_NOT_FOUND = "user.not_found"
    USER_ROLE_INVALID = "user.role_invalid"
    USER_SELF_DELETE_FORBIDDEN = "user.self_delete_forbidden"
    USER_INACTIVE = "user.inactive"

    EXPERIENCE_NOT_FOUND = "experience.not_found"
    EXPERIENCE_SLUG_ALREADY_EXISTS = "experience.slug_already_exists"
    EXPERIENCE_INVALID_DURATION = "experience.invalid_duration"
    EXPERIENCE_INVALID_CAPACITY = "experience.invalid_capacity"
    EXPERIENCE_PRICING_TIERS_REQUIRED = "experience.pricing_tiers_required"
    EXPERIENCE_PRICING_TIER_INVALID_RANGE = "experience.pricing_tier_invalid_range"
    EXPERIENCE_PRICING_TIERS_OVERLAP = "experience.pricing_tiers_overlap"
    EXPERIENCE_PRICING_TIERS_GAP = "experience.pricing_tiers_gap"
    EXPERIENCE_ROUTE_DURATION_EXCEEDS_ACTIVITY_DURATION = (
        "experience.route_duration_exceeds_activity_duration"
    )
    EXPERIENCE_STANDARD_CAPACITY_OUT_OF_PRICING_RANGE = (
        "experience.standard_capacity_out_of_pricing_range"
    )
    EXPERIENCE_INCLUSIONS_REQUIRED = "experience.inclusions_required"
    EXPERIENCE_INACTIVE = "experience.inactive"
    EXPERIENCE_PRICING_MISSING = "experience.pricing_missing"
    EXPERIENCE_PRICING_TIER_NOT_FOUND = "experience.pricing_tier_not_found"
    SCHEDULE_EXPERIENCE_MISMATCH = "schedule.experience_mismatch"

    SCHEDULE_NOT_FOUND = "schedule.not_found"
    SCHEDULE_INVALID_CAPACITY = "schedule.invalid_capacity"
    SCHEDULE_INVALID_SLOT_VALUES = "schedule.invalid_slot_values"
    SCHEDULE_NEGATIVE_AVAILABILITY = "schedule.negative_availability"
    SCHEDULE_NOT_OPEN = "schedule.not_open"
    SCHEDULE_ALREADY_FULL = "schedule.already_full"
    SCHEDULE_INVALID_STATUS = "schedule.invalid_status"

    RESERVATION_NOT_FOUND = "reservation.not_found"
    RESERVATION_INVALID_STATUS_TRANSITION = "reservation.invalid_status_transition"
    RESERVATION_MIN_NOTICE_VIOLATION = "reservation.min_notice_violation"
    RESERVATION_NO_AVAILABILITY = "reservation.no_availability"
    RESERVATION_PAYMENT_REQUIRED = "reservation.payment_required"
    RESERVATION_PAYMENT_NOT_VERIFIED = "reservation.payment_not_verified"
    RESERVATION_INVALID_PARTICIPANT_COUNT = "reservation.invalid_participant_count"
    RESERVATION_SCHEDULE_MISMATCH = "reservation.schedule_mismatch"
    RESERVATION_CONFIRMATION_NOT_ALLOWED = "reservation.confirmation_not_allowed"
    RESERVATION_CANCELLATION_NOT_ALLOWED = "reservation.cancellation_not_allowed"
    RESERVATION_ALREADY_CANCELLED = "reservation.already_cancelled"
    RESERVATION_ALREADY_COMPLETED = "reservation.already_completed"
    RESERVATION_PRE_RESERVATION_EXPIRED = "reservation.pre_reservation_expired"
    RESERVATION_ALREADY_PRE_RESERVED = "reservation.already_pre_reserved"
    RESERVATION_INVALID_HOLDER = "reservation.invalid_holder"
    RESERVATION_QUOTE_SNAPSHOT_REQUIRED = "reservation.quote_snapshot_required"
    SCHEDULE_HOLD_FAILED = "schedule.hold_failed"
    SCHEDULE_HELD_SLOTS_NEGATIVE = "schedule.held_slots_negative"

    PAYMENT_PROOF_NOT_FOUND = "payment_proof.not_found"
    PAYMENT_PROOF_STORAGE_KEY_REQUIRED = "payment_proof.storage_key_required"
    PAYMENT_PROOF_INVALID_CONTENT_TYPE = "payment_proof.invalid_content_type"
    PAYMENT_PROOF_INVALID_SIZE = "payment_proof.invalid_size"
    PAYMENT_PROOF_HASH_REQUIRED = "payment_proof.hash_required"
    PAYMENT_PROOF_RESERVATION_MISMATCH = "payment_proof.reservation_mismatch"

    PARTICIPANT_FORM_INVALID_TOKEN = "participant_form.invalid_token"
    PARTICIPANT_FORM_EXPIRED = "participant_form.expired"
    PARTICIPANT_FORM_FULL = "participant_form.full"
    PARTICIPANT_FORM_NOT_CONFIRMED = "participant_form.not_confirmed"
    PARTICIPANT_FORM_ALREADY_EXISTS = "participant_form.already_exists"

    PARTICIPANT_NOT_FOUND = "participant.not_found"
    PARTICIPANT_RESERVATION_MISMATCH = "participant.reservation_mismatch"
    PARTICIPANT_MISSING_REQUIRED_FIELDS = "participant.missing_required_fields"
    PARTICIPANT_INVALID_BIRTH_DATE = "participant.invalid_birth_date"
    PARTICIPANT_INVALID_WEIGHT = "participant.invalid_weight"
    PARTICIPANT_INVALID_HEIGHT = "participant.invalid_height"
    PARTICIPANT_DATA_PROCESSING_REQUIRED = "participant.data_processing_required"
    PARTICIPANT_OPERATIONALLY_INCOMPLETE = "participant.operationally_incomplete"

    EQUINE_NOT_FOUND = "equine.not_found"
    EQUINE_UNAVAILABLE = "equine.unavailable"
    EQUINE_INVALID_WEIGHT = "equine.invalid_weight"

    SADDLE_NOT_FOUND = "saddle.not_found"
    SADDLE_CODE_ALREADY_EXISTS = "saddle.code_already_exists"
    SADDLE_UNAVAILABLE = "saddle.unavailable"

    ASSIGNMENT_NOT_FOUND = "assignment.not_found"
    ASSIGNMENT_PARTICIPANT_NOT_IN_RESERVATION = "assignment.participant_not_in_reservation"
    ASSIGNMENT_EQUINE_ALREADY_ASSIGNED = "assignment.equine_already_assigned"
    ASSIGNMENT_SADDLE_ALREADY_ASSIGNED = "assignment.saddle_already_assigned"
    ASSIGNMENT_INVALID_PRIORITY = "assignment.invalid_priority"

    LOG_NOT_FOUND = "log.not_found"
    LOG_CHECKPOINT_NAME_REQUIRED = "log.checkpoint_name_required"
    LOG_INVALID_EVENT_TYPE = "log.invalid_event_type"

    PROVIDER_NOT_FOUND = "provider.not_found"
    POLICY_NOT_FOUND = "policy.not_found"
    POLICY_RESERVATION_MISMATCH = "policy.reservation_mismatch"
    CONFIG_NOT_FOUND = "config.not_found"
    CONFIG_INVALID_MIN_DAYS = "config.invalid_min_days"
    SYNC_STALE_VERSION = "sync.stale_version"
    SYNC_UNSUPPORTED_OPERATION = "sync.unsupported_operation"
    SYNC_INVALID_CURSOR = "sync.invalid_cursor"
    FILE_UPLOAD_NOT_FOUND = "file_upload.not_found"
    FILE_UPLOAD_EXPIRED = "file_upload.expired"
    FILE_UPLOAD_NOT_READY = "file_upload.not_ready"
