part of 'phone_country.dart';

const kPhoneCountries = <PhoneCountry>[
  PhoneCountry(iso: 'AF', name: 'Afghanistan', dialCode: '93'),
  PhoneCountry(iso: 'AL', name: 'Albania', dialCode: '355'),
  PhoneCountry(iso: 'DZ', name: 'Algeria', dialCode: '213'),
  PhoneCountry(iso: 'AS', name: 'American Samoa', dialCode: '1'),
  PhoneCountry(iso: 'AD', name: 'Andorra', dialCode: '376'),
  PhoneCountry(iso: 'AO', name: 'Angola', dialCode: '244'),
  PhoneCountry(iso: 'AI', name: 'Anguilla', dialCode: '1'),
  PhoneCountry(iso: 'AG', name: 'Antigua and Barbuda', dialCode: '1'),
  PhoneCountry(iso: 'AR', name: 'Argentina', dialCode: '54'),
  PhoneCountry(iso: 'AM', name: 'Armenia', dialCode: '374'),
  PhoneCountry(iso: 'AW', name: 'Aruba', dialCode: '297'),
  PhoneCountry(iso: 'AU', name: 'Australia', dialCode: '61'),
  PhoneCountry(iso: 'AT', name: 'Austria', dialCode: '43'),
  PhoneCountry(iso: 'AZ', name: 'Azerbaijan', dialCode: '994'),
  PhoneCountry(iso: 'BS', name: 'Bahamas', dialCode: '1'),
  PhoneCountry(iso: 'BH', name: 'Bahrain', dialCode: '973'),
  PhoneCountry(iso: 'BD', name: 'Bangladesh', dialCode: '880'),
  PhoneCountry(iso: 'BB', name: 'Barbados', dialCode: '1'),
  PhoneCountry(iso: 'BY', name: 'Belarus', dialCode: '375'),
  PhoneCountry(iso: 'BE', name: 'Belgium', dialCode: '32'),
  PhoneCountry(iso: 'BZ', name: 'Belize', dialCode: '501'),
  PhoneCountry(iso: 'BJ', name: 'Benin', dialCode: '229'),
  PhoneCountry(iso: 'BM', name: 'Bermuda', dialCode: '1'),
  PhoneCountry(iso: 'BT', name: 'Bhutan', dialCode: '975'),
  PhoneCountry(iso: 'BO', name: 'Bolivia', dialCode: '591'),
  PhoneCountry(iso: 'BA', name: 'Bosnia and Herzegovina', dialCode: '387'),
  PhoneCountry(iso: 'BW', name: 'Botswana', dialCode: '267'),
  PhoneCountry(iso: 'BR', name: 'Brazil', dialCode: '55'),
  PhoneCountry(iso: 'BN', name: 'Brunei', dialCode: '673'),
  PhoneCountry(iso: 'BG', name: 'Bulgaria', dialCode: '359'),
  PhoneCountry(iso: 'BF', name: 'Burkina Faso', dialCode: '226'),
  PhoneCountry(iso: 'BI', name: 'Burundi', dialCode: '257'),
  PhoneCountry(iso: 'KH', name: 'Cambodia', dialCode: '855'),
  PhoneCountry(iso: 'CM', name: 'Cameroon', dialCode: '237'),
  PhoneCountry(iso: 'CA', name: 'Canada', dialCode: '1'),
  PhoneCountry(iso: 'CV', name: 'Cape Verde', dialCode: '238'),
  PhoneCountry(iso: 'KY', name: 'Cayman Islands', dialCode: '1'),
  PhoneCountry(iso: 'CF', name: 'Central African Republic', dialCode: '236'),
  PhoneCountry(iso: 'TD', name: 'Chad', dialCode: '235'),
  PhoneCountry(iso: 'CL', name: 'Chile', dialCode: '56'),
  PhoneCountry(iso: 'CN', name: 'China', dialCode: '86'),
  PhoneCountry(iso: 'CO', name: 'Colombia', dialCode: '57'),
  PhoneCountry(iso: 'KM', name: 'Comoros', dialCode: '269'),
  PhoneCountry(iso: 'CG', name: 'Congo', dialCode: '242'),
  PhoneCountry(iso: 'CD', name: 'Congo (DRC)', dialCode: '243'),
  PhoneCountry(iso: 'CR', name: 'Costa Rica', dialCode: '506'),
  PhoneCountry(iso: 'CI', name: 'Cote d\'Ivoire', dialCode: '225'),
  PhoneCountry(iso: 'HR', name: 'Croatia', dialCode: '385'),
  PhoneCountry(iso: 'CU', name: 'Cuba', dialCode: '53'),
  PhoneCountry(iso: 'CY', name: 'Cyprus', dialCode: '357'),
  PhoneCountry(iso: 'CZ', name: 'Czechia', dialCode: '420'),
  PhoneCountry(iso: 'DK', name: 'Denmark', dialCode: '45'),
  PhoneCountry(iso: 'DJ', name: 'Djibouti', dialCode: '253'),
  PhoneCountry(iso: 'DM', name: 'Dominica', dialCode: '1'),
  PhoneCountry(iso: 'DO', name: 'Dominican Republic', dialCode: '1'),
  PhoneCountry(iso: 'EC', name: 'Ecuador', dialCode: '593'),
  PhoneCountry(iso: 'EG', name: 'Egypt', dialCode: '20'),
  PhoneCountry(iso: 'SV', name: 'El Salvador', dialCode: '503'),
  PhoneCountry(iso: 'GQ', name: 'Equatorial Guinea', dialCode: '240'),
  PhoneCountry(iso: 'ER', name: 'Eritrea', dialCode: '291'),
  PhoneCountry(iso: 'EE', name: 'Estonia', dialCode: '372'),
  PhoneCountry(iso: 'SZ', name: 'Eswatini', dialCode: '268'),
  PhoneCountry(iso: 'ET', name: 'Ethiopia', dialCode: '251'),
  PhoneCountry(iso: 'FK', name: 'Falkland Islands', dialCode: '500'),
  PhoneCountry(iso: 'FO', name: 'Faroe Islands', dialCode: '298'),
  PhoneCountry(iso: 'FJ', name: 'Fiji', dialCode: '679'),
  PhoneCountry(iso: 'FI', name: 'Finland', dialCode: '358'),
  PhoneCountry(iso: 'FR', name: 'France', dialCode: '33'),
  PhoneCountry(iso: 'GF', name: 'French Guiana', dialCode: '594'),
  PhoneCountry(iso: 'PF', name: 'French Polynesia', dialCode: '689'),
  PhoneCountry(iso: 'GA', name: 'Gabon', dialCode: '241'),
  PhoneCountry(iso: 'GM', name: 'Gambia', dialCode: '220'),
  PhoneCountry(iso: 'GE', name: 'Georgia', dialCode: '995'),
  PhoneCountry(iso: 'DE', name: 'Germany', dialCode: '49'),
  PhoneCountry(iso: 'GH', name: 'Ghana', dialCode: '233'),
  PhoneCountry(iso: 'GI', name: 'Gibraltar', dialCode: '350'),
  PhoneCountry(iso: 'GR', name: 'Greece', dialCode: '30'),
  PhoneCountry(iso: 'GL', name: 'Greenland', dialCode: '299'),
  PhoneCountry(iso: 'GD', name: 'Grenada', dialCode: '1'),
  PhoneCountry(iso: 'GP', name: 'Guadeloupe', dialCode: '590'),
  PhoneCountry(iso: 'GU', name: 'Guam', dialCode: '1'),
  PhoneCountry(iso: 'GT', name: 'Guatemala', dialCode: '502'),
  PhoneCountry(iso: 'GN', name: 'Guinea', dialCode: '224'),
  PhoneCountry(iso: 'GW', name: 'Guinea-Bissau', dialCode: '245'),
  PhoneCountry(iso: 'GY', name: 'Guyana', dialCode: '592'),
  PhoneCountry(iso: 'HT', name: 'Haiti', dialCode: '509'),
  PhoneCountry(iso: 'HN', name: 'Honduras', dialCode: '504'),
  PhoneCountry(iso: 'HK', name: 'Hong Kong', dialCode: '852'),
  PhoneCountry(iso: 'HU', name: 'Hungary', dialCode: '36'),
  PhoneCountry(iso: 'IS', name: 'Iceland', dialCode: '354'),
  PhoneCountry(iso: 'IN', name: 'India', dialCode: '91'),
  PhoneCountry(iso: 'ID', name: 'Indonesia', dialCode: '62'),
  PhoneCountry(iso: 'IR', name: 'Iran', dialCode: '98'),
  PhoneCountry(iso: 'IQ', name: 'Iraq', dialCode: '964'),
  PhoneCountry(iso: 'IE', name: 'Ireland', dialCode: '353'),
  PhoneCountry(iso: 'IL', name: 'Israel', dialCode: '972'),
  PhoneCountry(iso: 'IT', name: 'Italy', dialCode: '39'),
  PhoneCountry(iso: 'JM', name: 'Jamaica', dialCode: '1'),
  PhoneCountry(iso: 'JP', name: 'Japan', dialCode: '81'),
  PhoneCountry(iso: 'JO', name: 'Jordan', dialCode: '962'),
  PhoneCountry(iso: 'KZ', name: 'Kazakhstan', dialCode: '7'),
  PhoneCountry(iso: 'KE', name: 'Kenya', dialCode: '254'),
  PhoneCountry(iso: 'KI', name: 'Kiribati', dialCode: '686'),
  PhoneCountry(iso: 'KW', name: 'Kuwait', dialCode: '965'),
  PhoneCountry(iso: 'KG', name: 'Kyrgyzstan', dialCode: '996'),
  PhoneCountry(iso: 'LA', name: 'Laos', dialCode: '856'),
  PhoneCountry(iso: 'LV', name: 'Latvia', dialCode: '371'),
  PhoneCountry(iso: 'LB', name: 'Lebanon', dialCode: '961'),
  PhoneCountry(iso: 'LS', name: 'Lesotho', dialCode: '266'),
  PhoneCountry(iso: 'LR', name: 'Liberia', dialCode: '231'),
  PhoneCountry(iso: 'LY', name: 'Libya', dialCode: '218'),
  PhoneCountry(iso: 'LI', name: 'Liechtenstein', dialCode: '423'),
  PhoneCountry(iso: 'LT', name: 'Lithuania', dialCode: '370'),
  PhoneCountry(iso: 'LU', name: 'Luxembourg', dialCode: '352'),
  PhoneCountry(iso: 'MO', name: 'Macao', dialCode: '853'),
  PhoneCountry(iso: 'MG', name: 'Madagascar', dialCode: '261'),
  PhoneCountry(iso: 'MW', name: 'Malawi', dialCode: '265'),
  PhoneCountry(iso: 'MY', name: 'Malaysia', dialCode: '60'),
  PhoneCountry(iso: 'MV', name: 'Maldives', dialCode: '960'),
  PhoneCountry(iso: 'ML', name: 'Mali', dialCode: '223'),
  PhoneCountry(iso: 'MT', name: 'Malta', dialCode: '356'),
  PhoneCountry(iso: 'MH', name: 'Marshall Islands', dialCode: '692'),
  PhoneCountry(iso: 'MQ', name: 'Martinique', dialCode: '596'),
  PhoneCountry(iso: 'MR', name: 'Mauritania', dialCode: '222'),
  PhoneCountry(iso: 'MU', name: 'Mauritius', dialCode: '230'),
  PhoneCountry(iso: 'MX', name: 'Mexico', dialCode: '52'),
  PhoneCountry(iso: 'FM', name: 'Micronesia', dialCode: '691'),
  PhoneCountry(iso: 'MD', name: 'Moldova', dialCode: '373'),
  PhoneCountry(iso: 'MC', name: 'Monaco', dialCode: '377'),
  PhoneCountry(iso: 'MN', name: 'Mongolia', dialCode: '976'),
  PhoneCountry(iso: 'ME', name: 'Montenegro', dialCode: '382'),
  PhoneCountry(iso: 'MS', name: 'Montserrat', dialCode: '1'),
  PhoneCountry(iso: 'MA', name: 'Morocco', dialCode: '212'),
  PhoneCountry(iso: 'MZ', name: 'Mozambique', dialCode: '258'),
  PhoneCountry(iso: 'MM', name: 'Myanmar', dialCode: '95'),
  PhoneCountry(iso: 'NA', name: 'Namibia', dialCode: '264'),
  PhoneCountry(iso: 'NR', name: 'Nauru', dialCode: '674'),
  PhoneCountry(iso: 'NP', name: 'Nepal', dialCode: '977'),
  PhoneCountry(iso: 'NL', name: 'Netherlands', dialCode: '31'),
  PhoneCountry(iso: 'NC', name: 'New Caledonia', dialCode: '687'),
  PhoneCountry(iso: 'NZ', name: 'New Zealand', dialCode: '64'),
  PhoneCountry(iso: 'NI', name: 'Nicaragua', dialCode: '505'),
  PhoneCountry(iso: 'NE', name: 'Niger', dialCode: '227'),
  PhoneCountry(iso: 'NG', name: 'Nigeria', dialCode: '234'),
  PhoneCountry(iso: 'KP', name: 'North Korea', dialCode: '850'),
  PhoneCountry(iso: 'MK', name: 'North Macedonia', dialCode: '389'),
  PhoneCountry(iso: 'NO', name: 'Norway', dialCode: '47'),
  PhoneCountry(iso: 'OM', name: 'Oman', dialCode: '968'),
  PhoneCountry(iso: 'PK', name: 'Pakistan', dialCode: '92'),
  PhoneCountry(iso: 'PW', name: 'Palau', dialCode: '680'),
  PhoneCountry(iso: 'PS', name: 'Palestine', dialCode: '970'),
  PhoneCountry(iso: 'PA', name: 'Panama', dialCode: '507'),
  PhoneCountry(iso: 'PG', name: 'Papua New Guinea', dialCode: '675'),
  PhoneCountry(iso: 'PY', name: 'Paraguay', dialCode: '595'),
  PhoneCountry(iso: 'PE', name: 'Peru', dialCode: '51'),
  PhoneCountry(iso: 'PH', name: 'Philippines', dialCode: '63'),
  PhoneCountry(iso: 'PL', name: 'Poland', dialCode: '48'),
  PhoneCountry(iso: 'PT', name: 'Portugal', dialCode: '351'),
  PhoneCountry(iso: 'PR', name: 'Puerto Rico', dialCode: '1'),
  PhoneCountry(iso: 'QA', name: 'Qatar', dialCode: '974'),
  PhoneCountry(iso: 'RE', name: 'Reunion', dialCode: '262'),
  PhoneCountry(iso: 'RO', name: 'Romania', dialCode: '40'),
  PhoneCountry(iso: 'RU', name: 'Russia', dialCode: '7'),
  PhoneCountry(iso: 'RW', name: 'Rwanda', dialCode: '250'),
  PhoneCountry(iso: 'KN', name: 'Saint Kitts and Nevis', dialCode: '1'),
  PhoneCountry(iso: 'LC', name: 'Saint Lucia', dialCode: '1'),
  PhoneCountry(iso: 'VC', name: 'Saint Vincent', dialCode: '1'),
  PhoneCountry(iso: 'WS', name: 'Samoa', dialCode: '685'),
  PhoneCountry(iso: 'SM', name: 'San Marino', dialCode: '378'),
  PhoneCountry(iso: 'ST', name: 'Sao Tome and Principe', dialCode: '239'),
  PhoneCountry(iso: 'SA', name: 'Saudi Arabia', dialCode: '966'),
  PhoneCountry(iso: 'SN', name: 'Senegal', dialCode: '221'),
  PhoneCountry(iso: 'RS', name: 'Serbia', dialCode: '381'),
  PhoneCountry(iso: 'SC', name: 'Seychelles', dialCode: '248'),
  PhoneCountry(iso: 'SL', name: 'Sierra Leone', dialCode: '232'),
  PhoneCountry(iso: 'SG', name: 'Singapore', dialCode: '65'),
  PhoneCountry(iso: 'SK', name: 'Slovakia', dialCode: '421'),
  PhoneCountry(iso: 'SI', name: 'Slovenia', dialCode: '386'),
  PhoneCountry(iso: 'SB', name: 'Solomon Islands', dialCode: '677'),
  PhoneCountry(iso: 'SO', name: 'Somalia', dialCode: '252'),
  PhoneCountry(iso: 'ZA', name: 'South Africa', dialCode: '27'),
  PhoneCountry(iso: 'KR', name: 'South Korea', dialCode: '82'),
  PhoneCountry(iso: 'SS', name: 'South Sudan', dialCode: '211'),
  PhoneCountry(iso: 'ES', name: 'Spain', dialCode: '34'),
  PhoneCountry(iso: 'LK', name: 'Sri Lanka', dialCode: '94'),
  PhoneCountry(iso: 'SD', name: 'Sudan', dialCode: '249'),
  PhoneCountry(iso: 'SR', name: 'Suriname', dialCode: '597'),
  PhoneCountry(iso: 'SE', name: 'Sweden', dialCode: '46'),
  PhoneCountry(iso: 'CH', name: 'Switzerland', dialCode: '41'),
  PhoneCountry(iso: 'SY', name: 'Syria', dialCode: '963'),
  PhoneCountry(iso: 'TW', name: 'Taiwan', dialCode: '886'),
  PhoneCountry(iso: 'TJ', name: 'Tajikistan', dialCode: '992'),
  PhoneCountry(iso: 'TZ', name: 'Tanzania', dialCode: '255'),
  PhoneCountry(iso: 'TH', name: 'Thailand', dialCode: '66'),
  PhoneCountry(iso: 'TL', name: 'Timor-Leste', dialCode: '670'),
  PhoneCountry(iso: 'TG', name: 'Togo', dialCode: '228'),
  PhoneCountry(iso: 'TO', name: 'Tonga', dialCode: '676'),
  PhoneCountry(iso: 'TT', name: 'Trinidad and Tobago', dialCode: '1'),
  PhoneCountry(iso: 'TN', name: 'Tunisia', dialCode: '216'),
  PhoneCountry(iso: 'TR', name: 'Turkey', dialCode: '90'),
  PhoneCountry(iso: 'TM', name: 'Turkmenistan', dialCode: '993'),
  PhoneCountry(iso: 'TC', name: 'Turks and Caicos', dialCode: '1'),
  PhoneCountry(iso: 'TV', name: 'Tuvalu', dialCode: '688'),
  PhoneCountry(iso: 'UG', name: 'Uganda', dialCode: '256'),
  PhoneCountry(iso: 'UA', name: 'Ukraine', dialCode: '380'),
  PhoneCountry(iso: 'AE', name: 'United Arab Emirates', dialCode: '971'),
  PhoneCountry(iso: 'GB', name: 'United Kingdom', dialCode: '44'),
  PhoneCountry(iso: 'US', name: 'United States', dialCode: '1'),
  PhoneCountry(iso: 'UY', name: 'Uruguay', dialCode: '598'),
  PhoneCountry(iso: 'UZ', name: 'Uzbekistan', dialCode: '998'),
  PhoneCountry(iso: 'VU', name: 'Vanuatu', dialCode: '678'),
  PhoneCountry(iso: 'VA', name: 'Vatican City', dialCode: '39'),
  PhoneCountry(iso: 'VE', name: 'Venezuela', dialCode: '58'),
  PhoneCountry(iso: 'VN', name: 'Vietnam', dialCode: '84'),
  PhoneCountry(iso: 'VI', name: 'Virgin Islands (US)', dialCode: '1'),
  PhoneCountry(iso: 'YE', name: 'Yemen', dialCode: '967'),
  PhoneCountry(iso: 'ZM', name: 'Zambia', dialCode: '260'),
  PhoneCountry(iso: 'ZW', name: 'Zimbabwe', dialCode: '263'),
];
