name: mobile_core
description: Core utilities, networking, and infrastructure for La Juana mobile.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
