"""Catalogo maestro de errores de negocio y matriz endpoint -> casos."""

from typing import TypedDict

from app.common.labels import ErrorCode


class BusinessErrorCase(TypedDict):
    http_status: int
    code: str
    name: str
    trigger: str
    detail_keys: tuple[str, ...]


class EndpointBusinessCases(TypedDict):
    cases_400: tuple[str, ...]
    cases_404: tuple[str, ...]
    cases_409: tuple[str, ...]


BUSINESS_ERROR_CASES: dict[str, BusinessErrorCase] = {
    "B400-001": {
        "http_status": 400,
        "code": ErrorCode.AUTH_PASSWORD_MISMATCH,
        "name": "Contrasena actual incorrecta",
        "trigger": "current_password no coincide con la credencial vigente",
        "detail_keys": ("user_id",),
    },
    "B400-002": {
        "http_status": 400,
        "code": ErrorCode.USER_ROLE_INVALID,
        "name": "Rol invalido",
        "trigger": "rol fuera del catalogo permitido",
        "detail_keys": ("provided_role",),
    },
    "B400-003": {
        "http_status": 400,
        "code": ErrorCode.EXPERIENCE_INVALID_DURATION,
        "name": "Duracion invalida",
        "trigger": "la experiencia no define una duracion coherente",
        "detail_keys": ("duration_hours", "duration_days"),
    },
    "B400-004": {
        "http_status": 400,
        "code": ErrorCode.EXPERIENCE_INVALID_CAPACITY,
        "name": "Capacidad base invalida",
        "trigger": "base_capacity no cumple reglas",
        "detail_keys": ("base_capacity",),
    },
    "B400-005": {
        "http_status": 400,
        "code": ErrorCode.SCHEDULE_INVALID_CAPACITY,
        "name": "Capacidad total invalida",
        "trigger": "capacity_total <= 0",
        "detail_keys": ("capacity_total",),
    },
    "B400-006": {
        "http_status": 400,
        "code": ErrorCode.SCHEDULE_INVALID_SLOT_VALUES,
        "name": "Cupos invalidos",
        "trigger": "reserved_slots, blocked_slots o internal_slots invalidos",
        "detail_keys": ("reserved_slots", "blocked_slots", "internal_slots"),
    },
    "B400-007": {
        "http_status": 400,
        "code": ErrorCode.SCHEDULE_NEGATIVE_AVAILABILITY,
        "name": "Disponibilidad negativa",
        "trigger": "available_slots calculado es negativo",
        "detail_keys": ("available_slots",),
    },
    "B400-008": {
        "http_status": 400,
        "code": ErrorCode.SCHEDULE_INVALID_STATUS,
        "name": "Estado de agenda invalido",
        "trigger": "status no permitido o incoherente",
        "detail_keys": ("status",),
    },
    "B400-009": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_INVALID_PARTICIPANT_COUNT,
        "name": "Cantidad de participantes invalida",
        "trigger": "participant_count <= 0",
        "detail_keys": ("participant_count",),
    },
    "B400-010": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_SCHEDULE_MISMATCH,
        "name": "Agenda incompatible con experiencia",
        "trigger": "schedule no corresponde a experience",
        "detail_keys": ("reservation_experience_id", "schedule_experience_id"),
    },
    "B400-011": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_MIN_NOTICE_VIOLATION,
        "name": "Anticipacion minima incumplida",
        "trigger": "dias de anticipacion menores al minimo",
        "detail_keys": ("required_days", "service_date"),
    },
    "B400-012": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_PAYMENT_REQUIRED,
        "name": "Pago requerido",
        "trigger": "politica exige pago o comprobante",
        "detail_keys": ("reservation_id",),
    },
    "B400-013": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_PAYMENT_NOT_VERIFIED,
        "name": "Pago no verificado",
        "trigger": "la politica exige verificacion explicita",
        "detail_keys": ("payment_status",),
    },
    "B400-014": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_CONFIRMATION_NOT_ALLOWED,
        "name": "Confirmacion no permitida",
        "trigger": "la reserva incumple una regla funcional de confirmacion",
        "detail_keys": ("reservation_status",),
    },
    "B400-015": {
        "http_status": 400,
        "code": ErrorCode.RESERVATION_CANCELLATION_NOT_ALLOWED,
        "name": "Cancelacion no permitida",
        "trigger": "la reserva no puede cancelarse en el estado actual",
        "detail_keys": ("reservation_status",),
    },
    "B400-016": {
        "http_status": 400,
        "code": ErrorCode.PAYMENT_PROOF_STORAGE_KEY_REQUIRED,
        "name": "Falta referencia de archivo",
        "trigger": "faltan storage_key o referencia persistible",
        "detail_keys": ("reservation_id",),
    },
    "B400-017": {
        "http_status": 400,
        "code": ErrorCode.PAYMENT_PROOF_INVALID_CONTENT_TYPE,
        "name": "Tipo de archivo invalido",
        "trigger": "content_type fuera de allowlist",
        "detail_keys": ("content_type",),
    },
    "B400-018": {
        "http_status": 400,
        "code": ErrorCode.PAYMENT_PROOF_INVALID_SIZE,
        "name": "Tamano de archivo invalido",
        "trigger": "size_bytes invalido",
        "detail_keys": ("size_bytes",),
    },
    "B400-019": {
        "http_status": 400,
        "code": ErrorCode.PAYMENT_PROOF_HASH_REQUIRED,
        "name": "Hash faltante",
        "trigger": "falta huella sha256 requerida",
        "detail_keys": ("reservation_id",),
    },
    "B400-020": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_INVALID_BIRTH_DATE,
        "name": "Fecha de nacimiento invalida",
        "trigger": "fecha futura o incoherente",
        "detail_keys": ("birth_date",),
    },
    "B400-021": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_INVALID_WEIGHT,
        "name": "Peso invalido",
        "trigger": "weight_kg invalido segun reglas",
        "detail_keys": ("weight_kg",),
    },
    "B400-022": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_INVALID_HEIGHT,
        "name": "Altura invalida",
        "trigger": "height_cm invalido segun reglas",
        "detail_keys": ("height_cm",),
    },
    "B400-023": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_DATA_PROCESSING_REQUIRED,
        "name": "Habeas data requerido",
        "trigger": "no se acepta tratamiento de datos",
        "detail_keys": ("participant_id",),
    },
    "B400-024": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_MISSING_REQUIRED_FIELDS,
        "name": "Campos obligatorios faltantes",
        "trigger": "faltan campos requeridos para completitud",
        "detail_keys": ("missing_fields",),
    },
    "B400-025": {
        "http_status": 400,
        "code": ErrorCode.PARTICIPANT_OPERATIONALLY_INCOMPLETE,
        "name": "Participante no apto operativamente",
        "trigger": "participante incompleto para operacion",
        "detail_keys": ("participant_id", "missing_fields"),
    },
    "B400-026": {
        "http_status": 400,
        "code": ErrorCode.EQUINE_INVALID_WEIGHT,
        "name": "Peso del equino invalido",
        "trigger": "weight_kg invalido cuando se informa",
        "detail_keys": ("weight_kg",),
    },
    "B400-027": {
        "http_status": 400,
        "code": ErrorCode.ASSIGNMENT_PARTICIPANT_NOT_IN_RESERVATION,
        "name": "Participante fuera de la reserva",
        "trigger": "participant no pertenece a reservation",
        "detail_keys": ("reservation_id", "participant_id"),
    },
    "B400-028": {
        "http_status": 400,
        "code": ErrorCode.ASSIGNMENT_INVALID_PRIORITY,
        "name": "Prioridad de asignacion invalida",
        "trigger": "priority fuera del catalogo",
        "detail_keys": ("priority",),
    },
    "B400-029": {
        "http_status": 400,
        "code": ErrorCode.LOG_INVALID_EVENT_TYPE,
        "name": "Tipo de evento invalido",
        "trigger": "event_type no soportado",
        "detail_keys": ("event_type",),
    },
    "B400-030": {
        "http_status": 400,
        "code": ErrorCode.LOG_CHECKPOINT_NAME_REQUIRED,
        "name": "Punto clave requerido",
        "trigger": "evento checkpoint sin checkpoint_name",
        "detail_keys": ("event_type",),
    },
    "B400-031": {
        "http_status": 400,
        "code": ErrorCode.CONFIG_INVALID_MIN_DAYS,
        "name": "Anticipacion minima invalida",
        "trigger": "min_days_in_advance invalido",
        "detail_keys": ("min_days_in_advance",),
    },
    "B400-032": {
        "http_status": 400,
        "code": ErrorCode.EXPERIENCE_PRICING_MISSING,
        "name": "Experiencia sin tarifas",
        "trigger": "pricing es nulo o tiers vacio",
        "detail_keys": ("experience_id",),
    },
    "B404-001": {
        "http_status": 404,
        "code": ErrorCode.USER_NOT_FOUND,
        "name": "Usuario no existe",
        "trigger": "usuario objetivo no existe",
        "detail_keys": ("user_id",),
    },
    "B404-002": {
        "http_status": 404,
        "code": ErrorCode.EXPERIENCE_NOT_FOUND,
        "name": "Experiencia no existe",
        "trigger": "experience referenciada no existe",
        "detail_keys": ("experience_id",),
    },
    "B404-003": {
        "http_status": 404,
        "code": ErrorCode.SCHEDULE_NOT_FOUND,
        "name": "Fecha operativa no existe",
        "trigger": "schedule referenciada no existe",
        "detail_keys": ("schedule_id",),
    },
    "B404-004": {
        "http_status": 404,
        "code": ErrorCode.RESERVATION_NOT_FOUND,
        "name": "Reserva no existe",
        "trigger": "reservation objetivo no existe",
        "detail_keys": ("reservation_id",),
    },
    "B404-005": {
        "http_status": 404,
        "code": ErrorCode.PAYMENT_PROOF_NOT_FOUND,
        "name": "Comprobante no existe",
        "trigger": "payment_proof objetivo no existe",
        "detail_keys": ("payment_proof_id",),
    },
    "B404-006": {
        "http_status": 404,
        "code": ErrorCode.PARTICIPANT_NOT_FOUND,
        "name": "Participante no existe",
        "trigger": "participant objetivo no existe",
        "detail_keys": ("participant_id",),
    },
    "B404-007": {
        "http_status": 404,
        "code": ErrorCode.EQUINE_NOT_FOUND,
        "name": "Equino no existe",
        "trigger": "equine objetivo no existe",
        "detail_keys": ("equine_id",),
    },
    "B404-008": {
        "http_status": 404,
        "code": ErrorCode.SADDLE_NOT_FOUND,
        "name": "Silla no existe",
        "trigger": "saddle objetivo no existe",
        "detail_keys": ("saddle_id",),
    },
    "B404-009": {
        "http_status": 404,
        "code": ErrorCode.ASSIGNMENT_NOT_FOUND,
        "name": "Asignacion no existe",
        "trigger": "assignment objetivo no existe",
        "detail_keys": ("assignment_id",),
    },
    "B404-010": {
        "http_status": 404,
        "code": ErrorCode.LOG_NOT_FOUND,
        "name": "Evento de bitacora no existe",
        "trigger": "log objetivo no existe",
        "detail_keys": ("log_id",),
    },
    "B404-011": {
        "http_status": 404,
        "code": ErrorCode.PROVIDER_NOT_FOUND,
        "name": "Proveedor no existe",
        "trigger": "provider objetivo no existe",
        "detail_keys": ("provider_id",),
    },
    "B404-012": {
        "http_status": 404,
        "code": ErrorCode.POLICY_NOT_FOUND,
        "name": "Poliza no existe",
        "trigger": "policy objetivo no existe",
        "detail_keys": ("policy_id",),
    },
    "B404-013": {
        "http_status": 404,
        "code": ErrorCode.CONFIG_NOT_FOUND,
        "name": "Configuracion no existe",
        "trigger": "config solicitada no existe",
        "detail_keys": ("config_key",),
    },
    "B409-001": {
        "http_status": 409,
        "code": ErrorCode.USER_EMAIL_ALREADY_EXISTS,
        "name": "Email duplicado",
        "trigger": "existe usuario con el mismo email",
        "detail_keys": ("email",),
    },
    "B409-002": {
        "http_status": 409,
        "code": ErrorCode.EXPERIENCE_SLUG_ALREADY_EXISTS,
        "name": "Slug duplicado",
        "trigger": "existe experiencia con el mismo slug",
        "detail_keys": ("slug",),
    },
    "B409-003": {
        "http_status": 409,
        "code": ErrorCode.SCHEDULE_NOT_OPEN,
        "name": "Fecha operativa cerrada",
        "trigger": "schedule no esta abierta",
        "detail_keys": ("schedule_id", "status"),
    },
    "B409-004": {
        "http_status": 409,
        "code": ErrorCode.SCHEDULE_ALREADY_FULL,
        "name": "Fecha operativa llena",
        "trigger": "schedule sin cupos disponibles",
        "detail_keys": ("schedule_id", "available_slots"),
    },
    "B409-005": {
        "http_status": 409,
        "code": ErrorCode.RESERVATION_INVALID_STATUS_TRANSITION,
        "name": "Transicion de estado invalida",
        "trigger": "transicion no permitida por maquina de estados",
        "detail_keys": ("current_status", "target_status"),
    },
    "B409-006": {
        "http_status": 409,
        "code": ErrorCode.RESERVATION_NO_AVAILABILITY,
        "name": "Sin disponibilidad para confirmar",
        "trigger": "cupos insuficientes para confirmar",
        "detail_keys": ("available_slots", "required_slots"),
    },
    "B409-007": {
        "http_status": 409,
        "code": ErrorCode.RESERVATION_ALREADY_CANCELLED,
        "name": "Reserva ya cancelada",
        "trigger": "reserva ya esta cancelada",
        "detail_keys": ("reservation_id",),
    },
    "B409-008": {
        "http_status": 409,
        "code": ErrorCode.RESERVATION_ALREADY_COMPLETED,
        "name": "Reserva ya completada",
        "trigger": "reserva ya esta completada",
        "detail_keys": ("reservation_id",),
    },
    "B409-009": {
        "http_status": 409,
        "code": ErrorCode.PAYMENT_PROOF_RESERVATION_MISMATCH,
        "name": "Comprobante no corresponde a reserva",
        "trigger": "payment_proof no coincide con reservation",
        "detail_keys": ("payment_proof_id", "reservation_id"),
    },
    "B409-010": {
        "http_status": 409,
        "code": ErrorCode.SADDLE_CODE_ALREADY_EXISTS,
        "name": "Codigo de silla duplicado",
        "trigger": "existe silla con mismo codigo",
        "detail_keys": ("code",),
    },
    "B409-011": {
        "http_status": 409,
        "code": ErrorCode.EQUINE_UNAVAILABLE,
        "name": "Equino no disponible",
        "trigger": "equino no disponible para asignacion",
        "detail_keys": ("equine_id",),
    },
    "B409-012": {
        "http_status": 409,
        "code": ErrorCode.SADDLE_UNAVAILABLE,
        "name": "Silla no disponible",
        "trigger": "silla no disponible para asignacion",
        "detail_keys": ("saddle_id",),
    },
    "B409-013": {
        "http_status": 409,
        "code": ErrorCode.ASSIGNMENT_EQUINE_ALREADY_ASSIGNED,
        "name": "Equino ya asignado",
        "trigger": "equino ya asignado en salida incompatible",
        "detail_keys": ("equine_id", "reservation_id"),
    },
    "B409-014": {
        "http_status": 409,
        "code": ErrorCode.ASSIGNMENT_SADDLE_ALREADY_ASSIGNED,
        "name": "Silla ya asignada",
        "trigger": "silla ya asignada en salida incompatible",
        "detail_keys": ("saddle_id", "reservation_id"),
    },
    "B409-015": {
        "http_status": 409,
        "code": ErrorCode.POLICY_RESERVATION_MISMATCH,
        "name": "Poliza no corresponde a reserva",
        "trigger": "policy no coincide con reservation informada",
        "detail_keys": ("policy_id", "reservation_id"),
    },
    "B409-016": {
        "http_status": 409,
        "code": ErrorCode.USER_SELF_DELETE_FORBIDDEN,
        "name": "Autoeliminacion no permitida",
        "trigger": "el actor intenta desactivarse a si mismo",
        "detail_keys": ("user_id",),
    },
    "B409-017": {
        "http_status": 409,
        "code": ErrorCode.EXPERIENCE_INACTIVE,
        "name": "Experiencia inactiva",
        "trigger": "is_active es False",
        "detail_keys": ("experience_id",),
    },
    "B409-018": {
        "http_status": 409,
        "code": ErrorCode.SCHEDULE_EXPERIENCE_MISMATCH,
        "name": "Horario no corresponde a experiencia",
        "trigger": "schedule.experience_id != experience_id",
        "detail_keys": ("experience_id", "schedule_id"),
    },
    "B409-019": {
        "http_status": 409,
        "code": ErrorCode.EXPERIENCE_PRICING_TIER_NOT_FOUND,
        "name": "Sin tarifa para cantidad de participantes",
        "trigger": "participants_count fuera de todos los tiers",
        "detail_keys": ("participant_count",),
    },
}


ENDPOINT_BUSINESS_CASES: dict[tuple[str, str], EndpointBusinessCases] = {
    ("POST", "/api/v1/auth/register"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": ("B409-001",),
    },
    ("POST", "/api/v1/auth/login"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("POST", "/api/v1/auth/refresh"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("POST", "/api/v1/auth/logout"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("POST", "/api/v1/auth/change-password"): {
        "cases_400": ("B400-001",),
        "cases_404": (),
        "cases_409": (),
    },
    ("GET", "/api/v1/auth/me"): {"cases_400": (), "cases_404": ("B404-001",), "cases_409": ()},
    ("POST", "/api/v1/users"): {
        "cases_400": ("B400-002",),
        "cases_404": (),
        "cases_409": ("B409-001",),
    },
    ("GET", "/api/v1/users"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/users/{user_id}"): {
        "cases_400": (),
        "cases_404": ("B404-001",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/users/{user_id}"): {
        "cases_400": ("B400-002",),
        "cases_404": ("B404-001",),
        "cases_409": ("B409-001",),
    },
    ("DELETE", "/api/v1/users/{user_id}"): {
        "cases_400": (),
        "cases_404": ("B404-001",),
        "cases_409": ("B409-016",),
    },
    ("POST", "/api/v1/experiences"): {
        "cases_400": ("B400-003", "B400-004"),
        "cases_404": (),
        "cases_409": ("B409-002",),
    },
    ("GET", "/api/v1/experiences"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/experiences/{experience_id}"): {
        "cases_400": (),
        "cases_404": ("B404-002",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/experiences/{experience_id}"): {
        "cases_400": ("B400-003", "B400-004"),
        "cases_404": ("B404-002",),
        "cases_409": ("B409-002",),
    },
    ("DELETE", "/api/v1/experiences/{experience_id}"): {
        "cases_400": (),
        "cases_404": ("B404-002",),
        "cases_409": (),
    },
    ("POST", "/api/v1/experiences/{experience_id}/quote"): {
        "cases_400": ("B400-032",),
        "cases_404": ("B404-002", "B404-003"),
        "cases_409": ("B409-017", "B409-018", "B409-019"),
    },
    ("POST", "/api/v1/schedules"): {
        "cases_400": ("B400-005", "B400-006", "B400-007", "B400-008"),
        "cases_404": ("B404-002",),
        "cases_409": (),
    },
    ("GET", "/api/v1/schedules"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/schedules/{schedule_id}"): {
        "cases_400": (),
        "cases_404": ("B404-003",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/schedules/{schedule_id}"): {
        "cases_400": ("B400-005", "B400-006", "B400-007", "B400-008"),
        "cases_404": ("B404-003",),
        "cases_409": (),
    },
    ("DELETE", "/api/v1/schedules/{schedule_id}"): {
        "cases_400": (),
        "cases_404": ("B404-003",),
        "cases_409": (),
    },
    ("POST", "/api/v1/reservations"): {
        "cases_400": ("B400-009", "B400-010"),
        "cases_404": ("B404-002", "B404-003"),
        "cases_409": (),
    },
    ("GET", "/api/v1/reservations/availability"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("GET", "/api/v1/reservations"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/reservations/{reservation_id}"): {
        "cases_400": (),
        "cases_404": ("B404-004",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/reservations/{reservation_id}"): {
        "cases_400": ("B400-009",),
        "cases_404": ("B404-004",),
        "cases_409": ("B409-005", "B409-007", "B409-008"),
    },
    ("POST", "/api/v1/reservations/{reservation_id}/status"): {
        "cases_400": (),
        "cases_404": ("B404-004",),
        "cases_409": ("B409-005",),
    },
    ("POST", "/api/v1/reservations/{reservation_id}/confirm"): {
        "cases_400": ("B400-011", "B400-012", "B400-013", "B400-014", "B400-025"),
        "cases_404": ("B404-004", "B404-003"),
        "cases_409": ("B409-003", "B409-004", "B409-005", "B409-006"),
    },
    ("POST", "/api/v1/reservations/{reservation_id}/cancel"): {
        "cases_400": ("B400-015",),
        "cases_404": ("B404-004",),
        "cases_409": ("B409-005", "B409-007", "B409-008"),
    },
    ("POST", "/api/v1/reservations/{reservation_id}/payment-proofs"): {
        "cases_400": ("B400-016", "B400-017", "B400-018", "B400-019"),
        "cases_404": ("B404-004",),
        "cases_409": (),
    },
    ("POST", "/api/v1/reservations/{reservation_id}/participants"): {
        "cases_400": ("B400-020", "B400-021", "B400-022", "B400-023", "B400-024", "B400-025"),
        "cases_404": ("B404-004",),
        "cases_409": (),
    },
    ("GET", "/api/v1/payment-proofs/{payment_proof_id}"): {
        "cases_400": (),
        "cases_404": ("B404-005",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/payment-proofs/{payment_proof_id}"): {
        "cases_400": (),
        "cases_404": ("B404-005", "B404-004"),
        "cases_409": ("B409-009",),
    },
    ("GET", "/api/v1/participants/{participant_id}"): {
        "cases_400": (),
        "cases_404": ("B404-006",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/participants/{participant_id}"): {
        "cases_400": ("B400-020", "B400-021", "B400-022", "B400-023", "B400-024"),
        "cases_404": ("B404-006",),
        "cases_409": (),
    },
    ("POST", "/api/v1/equines"): {"cases_400": ("B400-026",), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/equines"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/equines/{equine_id}"): {
        "cases_400": (),
        "cases_404": ("B404-007",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/equines/{equine_id}"): {
        "cases_400": ("B400-026",),
        "cases_404": ("B404-007",),
        "cases_409": (),
    },
    ("DELETE", "/api/v1/equines/{equine_id}"): {
        "cases_400": (),
        "cases_404": ("B404-007",),
        "cases_409": (),
    },
    ("POST", "/api/v1/saddles"): {"cases_400": (), "cases_404": (), "cases_409": ("B409-010",)},
    ("GET", "/api/v1/saddles"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/saddles/{saddle_id}"): {
        "cases_400": (),
        "cases_404": ("B404-008",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/saddles/{saddle_id}"): {
        "cases_400": (),
        "cases_404": ("B404-008",),
        "cases_409": ("B409-010",),
    },
    ("POST", "/api/v1/assignments"): {
        "cases_400": ("B400-027", "B400-028"),
        "cases_404": ("B404-004", "B404-006", "B404-007", "B404-008"),
        "cases_409": ("B409-011", "B409-012", "B409-013", "B409-014"),
    },
    ("GET", "/api/v1/assignments/{assignment_id}"): {
        "cases_400": (),
        "cases_404": ("B404-009",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/assignments/{assignment_id}"): {
        "cases_400": (),
        "cases_404": ("B404-009", "B404-007", "B404-008"),
        "cases_409": ("B409-011", "B409-012", "B409-013", "B409-014"),
    },
    ("POST", "/api/v1/logs"): {
        "cases_400": ("B400-029", "B400-030"),
        "cases_404": ("B404-004",),
        "cases_409": (),
    },
    ("GET", "/api/v1/logs/{log_id}"): {
        "cases_400": (),
        "cases_404": ("B404-010",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/logs/{log_id}"): {
        "cases_400": ("B400-029", "B400-030"),
        "cases_404": ("B404-010",),
        "cases_409": (),
    },
    ("POST", "/api/v1/providers"): {"cases_400": (), "cases_404": (), "cases_409": ()},
    ("GET", "/api/v1/providers/{provider_id}"): {
        "cases_400": (),
        "cases_404": ("B404-011",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/providers/{provider_id}"): {
        "cases_400": (),
        "cases_404": ("B404-011",),
        "cases_409": (),
    },
    ("DELETE", "/api/v1/providers/{provider_id}"): {
        "cases_400": (),
        "cases_404": ("B404-011",),
        "cases_409": (),
    },
    ("POST", "/api/v1/policies"): {
        "cases_400": (),
        "cases_404": ("B404-004", "B404-011"),
        "cases_409": (),
    },
    ("GET", "/api/v1/policies/{policy_id}"): {
        "cases_400": (),
        "cases_404": ("B404-012",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/policies/{policy_id}"): {
        "cases_400": (),
        "cases_404": ("B404-012",),
        "cases_409": ("B409-015",),
    },
    ("GET", "/api/v1/config/emergency-contacts"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("GET", "/api/v1/config/reservation-rules"): {
        "cases_400": (),
        "cases_404": ("B404-013",),
        "cases_409": (),
    },
    ("PATCH", "/api/v1/config/reservation-rules"): {
        "cases_400": ("B400-031",),
        "cases_404": ("B404-013",),
        "cases_409": (),
    },
    ("GET", "/api/v1/sync/bootstrap"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("POST", "/api/v1/sync/pull"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("POST", "/api/v1/sync/push"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("POST", "/api/v1/files/init-upload"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
    ("POST", "/api/v1/files/{upload_id}/complete"): {
        "cases_400": (),
        "cases_404": (),
        "cases_409": (),
    },
}
